//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playerok.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.OrdersGame = new HashSet<OrdersGame>();
        }
    
        public int ID_game { get; set; }
        public string Name { get; set; }
        public int ID_genre { get; set; }
        public int Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Developer { get; set; }
        public System.DateTime Release_date { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    
        public virtual Genres Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersGame> OrdersGame { get; set; }
    }
}
